### PR TITLE
Add ffmpeg@9.0.1.beta.bcr

### PR DESCRIPTION
**Pull request by dzbarsky**
Adds `ffmpeg@9.0.1.beta.bcr` from the official FFmpeg 9.0.1 archive, retaining the beta designation requested in review. The port updates component declarations, source selections, AArch64/NASM inputs, and configuration for FFmpeg 9 while preserving the existing bare and `with_defaults/` targets, default component profiles, install trees, and upstream tests. It also retains the BoringSSL compatibility and shared-library helper fixes; `libpostproc` was removed upstream. `CONFIG_LIST` and `PROFILE_EVERYTHING` use one entry per line so future component changes produce smaller diffs; the generator and formatting tests preserve that layout.

Integrates `codec2`, `dav1d`, `gsm`, `lame`, `libjxl`, `openjpeg`, `rav1e`, `shine`, `speex`, `twolame`, `vorbis`, and `xvidcore` from #10262 through 21 optional encoder/decoder flags. All remain disabled by default. Library configuration follows the selected components, including LAME/Vorbis muxer defaults; JPEG XL animation flags work without the still-image flags. FFmpeg continues to report upstream version `9.0.1`. The README documents the flags and the GPLv3 license-reporting policy for external GPL codecs without enabling FFmpeg's internal GPL implementations.

All prerequisite module changes are merged in #10262, #10270, and #10272. This branch is rebased onto `main`, and this PR now changes only `modules/ffmpeg/`. It uses `libjxl@0.12.0.bcr.1`, whose GoogleTest dependency avoids the Abseil compatibility-level conflict on Bazel 8.5. FFmpeg requires Bazel 8.5.0 for `rav1e`/`rules_rs`. Presubmit retains all five FFmpeg platforms, tests Bazel 8.5.0/8.x/9.x, enables all new codecs in the extras task, and adds an animation-only JPEG XL task.

Uses `brotli@1.2.0.bcr.3`, `skcms@20250916.0.bcr.2`, and `x264@2023.10.1.bcr.3` from #10270. These fix GCC 8 compilation errors and inconsistent x264 download checksums found by the first complete FFmpeg CI run. JPEG XL requests the corrected Brotli/skcms revisions, and FFmpeg requests the corrected x264 revision.

Local validation after the dependency fixes passes all 57 tests on Bazel 8.5 with macOS ARM64/Clang 21: FFmpeg's 52 tests with every optional codec enabled, both new dependency regression tests, and JPEG XL's three existing tests. The same 57 tests also pass for macOS x86_64 on Bazel 9.2. The integration tests cover all 21 registrations and all 13 encoders, including encode/decode round trips. Earlier validation of the unchanged FFmpeg implementation also passed the full default, BoringSSL, animation-only, encoder-only, and decoder-only tests on Bazel 8.5/9.2. All 36 Python tests, byte-identical regeneration of six generated files, Buildifier, and the BCR-pinned Ruff checks pass. The list formatting preserves every component value and its order. GCC 8.5 validation of the prerequisite fixes passes Brotli's strict build, rotation test, and CLI round trip, plus skcms's full SIMD build and transform test in all three compilation modes.

CI passes all 46 FFmpeg configurations on the rebased commit with the list formatting change, including all 15 Bazel 8.x incompatible-flag reruns. Registry validation, formatting, tooling checks, and CLA checks are also green. [Buildkite results](https://buildkite.com/bazel/bcr-presubmit/builds/40229). The prerequisite configurations passed separately in #10270 and #10272. FFmpeg uses the official release archive and passes URL-stability validation without an exception.

-zbarskybot

### CODE REVIEW

**Comment by bazel-io** [comment]
Hello @uebelandre, modules you maintain (ffmpeg) have been updated in this PR.
      Please review the changes. You can view a diff against the previous version in the "Generate module diff" check.

**Review by UebelAndre — CHANGES_REQUESTED** [review]
Awesome! I'm curious what your thoughts are on the implementation here and whether or not you feel it's worth of being promoted from the `.beta.bcr` version. I'm happy to accept more aggressive changes if there's some documentation about how the changes improve parity with ffmpeg's configure+make implementation.

**Comment by dzbarsky** [comment]
> Awesome! I'm curious what your thoughts are on the implementation here and whether or not you feel it's worth of being promoted from the `.beta.bcr` version. I'm happy to accept more aggressive changes if there's some documentation about how the changes improve parity with ffmpeg's configure+make implementation.

I think the upstream build is unfortunately pretty convoluted which results in a pretty complex implementation in the bazel world. I think you did a pretty good abstracting out some things that make it fairly easy for agents to follow the pattern, which is great!

I had forgotten the beta.bcr version thing, we can tag this as `9.0.1.beta.bcr` instead! I also have a bunch more codecs in https://github.com/bazelbuild/bazel-central-registry/pull/10258 that we should include here as well with the optional flags, once those merge

**Comment by UebelAndre** [comment]
Ping me whenever the intermediates are merged and this is ready for review again!

**Comment by dzbarsky** [comment]
`libjxl@0.12.0.bcr.1` reuses exactly the source URL and SHA256 already accepted for `libjxl@0.12.0` in #10262. The JPEG XL 0.12.0 release publishes binary packages but no source release asset; the revision changes only BCR module metadata and adds Bazel 8.5.0 coverage to the existing tests.

The `skip-url-stability-check` label requests BCR's documented exception for this unchanged archive. Archive integrity and source-repository checks remain enabled.

-zbarskybot

**Comment by bazel-io** [comment]
Hello BCR maintainers, modules (libjxl) have been updated in this PR.
        Please review the changes. You can view a diff against the previous version in the "Generate module diff" check.

**Comment by bazel-io** [comment]
Hello @eustas, modules you maintain (brotli, skcms) have been updated in this PR.
      Please review the changes. You can view a diff against the previous version in the "Generate module diff" check.

**Comment by bazel-io** [comment]
Hello @uebelandre, modules you maintain (ffmpeg, x264) have been updated in this PR.
      Please review the changes. You can view a diff against the previous version in the "Generate module diff" check.

**Comment by dzbarsky** [comment]
@UebelAndre landed all the deps and rebased, PTAL!

**Review by abrisco — APPROVED** [review]
Thank you!

**Review by UebelAndre — APPROVED** [review]
Thank you!
